# Generated by Django 2.1.3 on 2018-11-28 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.TextField()),
                ('ResolvedValue', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LabAttendent',
            fields=[
                ('AttendentName', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('LabAssigned', models.TextField()),
                ('Contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LabInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabName', models.CharField(blank=True, max_length=20)),
                ('LabCapacity', models.IntegerField(null=True)),
                ('SoftwareInstalled', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeSlot', models.CharField(blank=True, max_length=7)),
                ('Batch', models.CharField(blank=True, max_length=8)),
                ('Day', models.CharField(blank=True, max_length=13)),
                ('Subject', models.CharField(blank=True, max_length=10)),
                ('LabName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.LabInfo')),
            ],
        ),
        migrations.CreateModel(
            name='LabTeacher',
            fields=[
                ('TeacherName', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('Contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssuedOn', models.DateField()),
                ('Text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='labschedule',
            name='TeacherName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.LabTeacher'),
        ),
        migrations.AddField(
            model_name='complains',
            name='LabName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.LabInfo'),
        ),
        migrations.AddField(
            model_name='complains',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
