# Generated by Django 2.1.3 on 2018-11-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('LabCapacity', models.IntegerField()),
                ('Software', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='complains',
            name='LabName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.LabInf'),
        ),
        migrations.AlterField(
            model_name='labschedule',
            name='LabName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.LabInf'),
        ),
        migrations.DeleteModel(
            name='LabInfo',
        ),
    ]
